# -*- coding: utf-8 -*-
"""global inflation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVhpGUfi9ZyBbNtfEpCATitOzF7_kiig
"""

import pandas as pd


df = pd.read_csv("/content/global_inflation_data.csv")

print("DataFrame Info:")
print(df.info())

print("\nFirst 5 Rows:")
print(df.head())

print("\nDescriptive Statistics:")
print(df.describe())

print("\nShape of the DataFrame:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nNull Values in Each Column:")
print(df.isnull().sum())

df.rename(columns=lambda x: x.strip().capitalize().replace('_', ''), inplace=True)

print("\nRenamed Columns:")
print(df.columns)

df.drop_duplicates(subset=['Countryname', 'Indicatorname'], keep='first', inplace=True)

print("\nShape after removing duplicates:")
print(df.shape)

df.fillna(0, inplace=True)

print("\nCheck if any null values remain:")
print(df.isnull().sum().sum())

for col in df.columns[2:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Countryname'] = df['Countryname'].astype(str).str.strip().str.title()
df['Indicatorname'] = df['Indicatorname'].astype(str).str.strip().str.lower()

print("\nDatatype check after conversion:")
print(df.dtypes)

df.to_csv("cleaned_global_inflation_data.csv", index=False)
print("\n✅ Cleaned dataset saved as 'cleaned_global_inflation_data.csv'")

df_long = df.melt(
    id_vars=['Countryname', 'Indicatorname'],
    var_name='Year',
    value_name='InflationRate'
)



df_long['Year'] = pd.to_datetime(df_long['Year'], format='%Y')


print("\nFirst 10 rows of reshaped data:")
print(df_long.head(10))


df_long.to_csv("tidy_global_inflation_data.csv", index=False)
print("\n✅ Tidy dataset saved as 'tidy_global_inflation_data.csv'")


print(df.isnull().sum())
print(df.dtypes)
print(df.info())
print(df_long.dtypes)

df.isna().sum()

df.dtypes